PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX iotsn: <http://iot.soton.ac.uk/smarthome/sensor#>
PREFIX iot: <http://purl.oclc.org/NET/iot#>

SELECT (avg(?val) as ?sval)
FROM NAMED STREAM <http://iot.soton.ac.uk/smarthome/environment> [RANGE 1h STEP]
WHERE {
  ?obs ssn:observedBy iotsn:environmental1;
    ssn:observationResult ?snout.
  ?snout ssn:hasValue ?obsval.
  ?obsval a iot:InternalTemperatureValue;
    iot:hasQuantityValue ?val.
}